export const SfwSelect = () => (
  <select>
    <option>waifu</option>
    <option>neko</option>
    <option>shinobu</option>
    <option>megumin</option>
    <option>bully</option>
    <option>cuddle</option>
    <option>cry</option>
    <option>hug</option>
    <option>awoo</option>
    <option>kiss</option>
    <option>lick</option>
    <option>pat</option>
    <option>smug</option>
    <option>bonk</option>
    <option>yeet</option>
    <option>blush</option>
    <option>smile</option>
    <option>wave</option>
    <option>highfive</option>
    <option>handhold</option>
    <option>nom</option>
    <option>bite</option>
    <option>glomp</option>
    <option>slap</option>
    <option>kill</option>
    <option>kick</option>
    <option>happy</option>
    <option>wink</option>
    <option>poke</option>
    <option>dance</option>
    <option>cringe</option>
  </select>
);
